# Generated by Django 5.1.4 on 2024-12-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="views_counter",
        ),
    ]
