# Generated by Django 5.1.4 on 2024-12-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_remove_product_views_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена за покупку",
                max_digits=10,
                verbose_name="Стоимость",
            ),
        ),
    ]
