# Generated by Django 5.1.4 on 2025-01-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_options_remove_product_views_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
