# Generated by Django 5.1.4 on 2025-01-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    (
                        "can_change_product_description",
                        "Can change product description",
                    ),
                    ("can_change_product_category", "Can change product category"),
                ]
            },
        ),
    ]
